"""services1.5

Revision ID: 5b400738ca5e
Revises: 68304f42a98a
Create Date: 2022-10-15 18:49:23.529604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b400738ca5e'
down_revision = '68304f42a98a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
