"""services1.7

Revision ID: 5ed3671b20b9
Revises: 8df4aff8e440
Create Date: 2022-10-15 19:21:41.247248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed3671b20b9'
down_revision = '8df4aff8e440'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
