"""services1.5

Revision ID: 68304f42a98a
Revises: b5555861626c
Create Date: 2022-10-12 21:04:24.338183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68304f42a98a'
down_revision = 'b5555861626c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
