"""services1.7

Revision ID: ca80aea1dfa7
Revises: 5ed3671b20b9
Create Date: 2022-10-15 19:24:10.762485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca80aea1dfa7'
down_revision = '5ed3671b20b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
